spring:
  application:
    name: Zuul-server


info:
  component: Edge Zuul Server
    
    
zuul:
  prefix: /api
  routes:
    account: 
      path: /accounts/**
      serviceId: Account-Service
    customer: 
      path: /customers/**
      serviceId: Customer-Service 
    
ribbon:
  eureka:
    enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
       
server:
  port: 8999
