server:
  port: 8502
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  application:
    name: student-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: student-service
      host: localhost
      port: 8500
      
  datasource:
    url: jdbc:mysql://localhost:3306/hiber
    username: root
    password: pass@word1
    driver-class-name: