server:
  port: 8086
  
spring:
  application:
    name: order-consumer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    consul:
      discovery:
        register: true
        service-name: order-consumer
      host: localhost
      port: 8500
