server:
  port: 8082
spring:
  application:
    name: product-service-feign

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true



      
  