server:
  port: 8082
spring:
  application:
    name: product-service-B

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true



      
  